### ISSUE TITLE
issue with Frusterick Manners?

### ISSUE THREAD

**Issue by jkester1986** [leeyc0/dokuwiki_plugin_color#4]
Your plugin doesn't seem to be working with Frusterick Manners - at least not on my site. The color tags are displaying instead of the color.

**Comment by leeyc0** [comment]
Please note that the plugin is not developed by me as stated in https://www.dokuwiki.org/plugin:color. The original user seems left this plugin unmaintained and I only move it to my github page for convenience only. I have no time to troubleshoot this but patches are welcome

**Comment by jkester1986** [comment]
Ok, thank you

**Comment by lpaulsen93** [comment]
@jkester1986: Seems to work for me. Here's an example wiki code:
```
gray gray <color blue/lightgray>color</color> gray gray <color #FF0000/#00ff00>another color</color> gray
```
If it still not works for you, could you provide your not working wiki code?

**Comment by jkester1986** [comment]
@LarsGit223 At this point I'm not even sure what I was doing, since it was almost a year ago. I re-installed and using your example it's working fine. Might have been a conflict with another plugin at the time, or something else *shrug*

**Comment by lpaulsen93** [comment]
Never mind. So if you no open problems please close this issue.
